name: fit_track_ai
description: "An AI-powered fitness transformation app that helps users track progress, predict physical changes, and stay motivated week-by-week."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0

  # State management
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.1.0

  # UI and UX
  cupertino_icons: ^1.0.8
  fl_chart: ^0.66.0
  google_fonts: ^6.2.0
  cached_network_image: ^4.0.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  animations: ^3.0.2

  # Image, File, API
  image_picker: ^1.0.8
  dio: ^6.2.0
  path_provider: ^3.0.0
  intl: ^0.19.0
  file_picker: ^6.2.0

  # Storage, Persistence
  shared_preferences: ^3.1.0

  # UX Add-ons
  fluttertoast: ^9.0.1
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.9
  riverpod_generator: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
