name: fit_track_ai
description: "An AI-powered fitness transformation app that helps users track progress, predict physical changes, and stay motivated week-by-week."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.0

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.4

  # UI and UX
  cupertino_icons: ^1.0.8
  fl_chart: ^1.0.0
  google_fonts: ^6.2.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  animations: ^2.0.11

  # Image, File, API
  image_picker: ^1.0.8
  dio: ^5.4.3+1
  path_provider: ^2.1.2
  intl: ^0.20.2
  file_picker: ^10.1.9

  # Storage, Persistence
  shared_preferences: ^2.2.2

  # UX Add-ons
  fluttertoast: ^8.2.4
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.3.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
